# Temporal dynamic config for local development with SQL persistence
# https://docs.temporal.io/references/dynamic-configuration

system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

limit.maxIDLength:
  - value: 255
    constraints: {}
