/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125AccountRouteImport } from './routes/{-$locale}/account'
import { Route as Char123LocaleChar125DesignSystemRouteImport } from './routes/{-$locale}/design-system'
import { Route as Char123LocaleChar125ForgotPasswordRouteImport } from './routes/{-$locale}/forgot-password'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125NotificationsRouteImport } from './routes/{-$locale}/notifications'
import { Route as Char123LocaleChar125OnboardingRouteImport } from './routes/{-$locale}/onboarding'
import { Route as Char123LocaleChar125RegisterRouteImport } from './routes/{-$locale}/register'
import { Route as Char123LocaleChar125ResetPasswordRouteImport } from './routes/{-$locale}/reset-password'
import { Route as Char123LocaleChar125ProjectsIndexRouteImport } from './routes/{-$locale}/projects/index'
import { Route as Char123LocaleChar125ProjectsIdRouteImport } from './routes/{-$locale}/projects/$id'
import { Route as Char123LocaleChar125UploadsIndexRouteImport } from './routes/{-$locale}/uploads/index'
import { Route as Char123LocaleChar125UploadsIdRouteImport } from './routes/{-$locale}/uploads/$id'
import { Route as Char123LocaleChar125ProjectsIdIndexRouteImport } from './routes/{-$locale}/projects/$id/index'
import { Route as Char123LocaleChar125ProjectsIdCopilotRouteImport } from './routes/{-$locale}/projects/$id/copilot'
import { Route as Char123LocaleChar125ProjectsIdDocumentsRouteImport } from './routes/{-$locale}/projects/$id/documents'
import { Route as Char123LocaleChar125ProjectsIdSubmissionRouteImport } from './routes/{-$locale}/projects/$id/submission'
import { Route as Char123LocaleChar125ProjectsIdCopilotIndexRouteImport } from './routes/{-$locale}/projects/$id/copilot/index'
import { Route as Char123LocaleChar125ProjectsIdCopilotConversationIdRouteImport } from './routes/{-$locale}/projects/$id/copilot/$conversationId'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountRoute =
  Char123LocaleChar125AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DesignSystemRoute =
  Char123LocaleChar125DesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ForgotPasswordRoute =
  Char123LocaleChar125ForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125NotificationsRoute =
  Char123LocaleChar125NotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125OnboardingRoute =
  Char123LocaleChar125OnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125RegisterRoute =
  Char123LocaleChar125RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ResetPasswordRoute =
  Char123LocaleChar125ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProjectsIndexRoute =
  Char123LocaleChar125ProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProjectsIdRoute =
  Char123LocaleChar125ProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125UploadsIndexRoute =
  Char123LocaleChar125UploadsIndexRouteImport.update({
    id: '/uploads/',
    path: '/uploads/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125UploadsIdRoute =
  Char123LocaleChar125UploadsIdRouteImport.update({
    id: '/uploads/$id',
    path: '/uploads/$id',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProjectsIdIndexRoute =
  Char123LocaleChar125ProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ProjectsIdRoute,
  } as any)
const Char123LocaleChar125ProjectsIdCopilotRoute =
  Char123LocaleChar125ProjectsIdCopilotRouteImport.update({
    id: '/copilot',
    path: '/copilot',
    getParentRoute: () => Char123LocaleChar125ProjectsIdRoute,
  } as any)
const Char123LocaleChar125ProjectsIdDocumentsRoute =
  Char123LocaleChar125ProjectsIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => Char123LocaleChar125ProjectsIdRoute,
  } as any)
const Char123LocaleChar125ProjectsIdSubmissionRoute =
  Char123LocaleChar125ProjectsIdSubmissionRouteImport.update({
    id: '/submission',
    path: '/submission',
    getParentRoute: () => Char123LocaleChar125ProjectsIdRoute,
  } as any)
const Char123LocaleChar125ProjectsIdCopilotIndexRoute =
  Char123LocaleChar125ProjectsIdCopilotIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ProjectsIdCopilotRoute,
  } as any)
const Char123LocaleChar125ProjectsIdCopilotConversationIdRoute =
  Char123LocaleChar125ProjectsIdCopilotConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => Char123LocaleChar125ProjectsIdCopilotRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/design-system': typeof Char123LocaleChar125DesignSystemRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/notifications': typeof Char123LocaleChar125NotificationsRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125OnboardingRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/projects/$id': typeof Char123LocaleChar125ProjectsIdRouteWithChildren
  '/{-$locale}/uploads/$id': typeof Char123LocaleChar125UploadsIdRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/uploads/': typeof Char123LocaleChar125UploadsIndexRoute
  '/{-$locale}/projects/$id/copilot': typeof Char123LocaleChar125ProjectsIdCopilotRouteWithChildren
  '/{-$locale}/projects/$id/documents': typeof Char123LocaleChar125ProjectsIdDocumentsRoute
  '/{-$locale}/projects/$id/submission': typeof Char123LocaleChar125ProjectsIdSubmissionRoute
  '/{-$locale}/projects/$id/': typeof Char123LocaleChar125ProjectsIdIndexRoute
  '/{-$locale}/projects/$id/copilot/$conversationId': typeof Char123LocaleChar125ProjectsIdCopilotConversationIdRoute
  '/{-$locale}/projects/$id/copilot/': typeof Char123LocaleChar125ProjectsIdCopilotIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/design-system': typeof Char123LocaleChar125DesignSystemRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/notifications': typeof Char123LocaleChar125NotificationsRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125OnboardingRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/uploads/$id': typeof Char123LocaleChar125UploadsIdRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/uploads': typeof Char123LocaleChar125UploadsIndexRoute
  '/{-$locale}/projects/$id/documents': typeof Char123LocaleChar125ProjectsIdDocumentsRoute
  '/{-$locale}/projects/$id/submission': typeof Char123LocaleChar125ProjectsIdSubmissionRoute
  '/{-$locale}/projects/$id': typeof Char123LocaleChar125ProjectsIdIndexRoute
  '/{-$locale}/projects/$id/copilot/$conversationId': typeof Char123LocaleChar125ProjectsIdCopilotConversationIdRoute
  '/{-$locale}/projects/$id/copilot': typeof Char123LocaleChar125ProjectsIdCopilotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AccountRoute
  '/{-$locale}/design-system': typeof Char123LocaleChar125DesignSystemRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/notifications': typeof Char123LocaleChar125NotificationsRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125OnboardingRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/projects/$id': typeof Char123LocaleChar125ProjectsIdRouteWithChildren
  '/{-$locale}/uploads/$id': typeof Char123LocaleChar125UploadsIdRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/uploads/': typeof Char123LocaleChar125UploadsIndexRoute
  '/{-$locale}/projects/$id/copilot': typeof Char123LocaleChar125ProjectsIdCopilotRouteWithChildren
  '/{-$locale}/projects/$id/documents': typeof Char123LocaleChar125ProjectsIdDocumentsRoute
  '/{-$locale}/projects/$id/submission': typeof Char123LocaleChar125ProjectsIdSubmissionRoute
  '/{-$locale}/projects/$id/': typeof Char123LocaleChar125ProjectsIdIndexRoute
  '/{-$locale}/projects/$id/copilot/$conversationId': typeof Char123LocaleChar125ProjectsIdCopilotConversationIdRoute
  '/{-$locale}/projects/$id/copilot/': typeof Char123LocaleChar125ProjectsIdCopilotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/design-system'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/notifications'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/'
    | '/{-$locale}/projects/$id'
    | '/{-$locale}/uploads/$id'
    | '/{-$locale}/projects/'
    | '/{-$locale}/uploads/'
    | '/{-$locale}/projects/$id/copilot'
    | '/{-$locale}/projects/$id/documents'
    | '/{-$locale}/projects/$id/submission'
    | '/{-$locale}/projects/$id/'
    | '/{-$locale}/projects/$id/copilot/$conversationId'
    | '/{-$locale}/projects/$id/copilot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/design-system'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/notifications'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}'
    | '/{-$locale}/uploads/$id'
    | '/{-$locale}/projects'
    | '/{-$locale}/uploads'
    | '/{-$locale}/projects/$id/documents'
    | '/{-$locale}/projects/$id/submission'
    | '/{-$locale}/projects/$id'
    | '/{-$locale}/projects/$id/copilot/$conversationId'
    | '/{-$locale}/projects/$id/copilot'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/design-system'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/notifications'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/'
    | '/{-$locale}/projects/$id'
    | '/{-$locale}/uploads/$id'
    | '/{-$locale}/projects/'
    | '/{-$locale}/uploads/'
    | '/{-$locale}/projects/$id/copilot'
    | '/{-$locale}/projects/$id/documents'
    | '/{-$locale}/projects/$id/submission'
    | '/{-$locale}/projects/$id/'
    | '/{-$locale}/projects/$id/copilot/$conversationId'
    | '/{-$locale}/projects/$id/copilot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account': {
      id: '/{-$locale}/account'
      path: '/account'
      fullPath: '/{-$locale}/account'
      preLoaderRoute: typeof Char123LocaleChar125AccountRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/design-system': {
      id: '/{-$locale}/design-system'
      path: '/design-system'
      fullPath: '/{-$locale}/design-system'
      preLoaderRoute: typeof Char123LocaleChar125DesignSystemRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/forgot-password': {
      id: '/{-$locale}/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125ForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/notifications': {
      id: '/{-$locale}/notifications'
      path: '/notifications'
      fullPath: '/{-$locale}/notifications'
      preLoaderRoute: typeof Char123LocaleChar125NotificationsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/onboarding': {
      id: '/{-$locale}/onboarding'
      path: '/onboarding'
      fullPath: '/{-$locale}/onboarding'
      preLoaderRoute: typeof Char123LocaleChar125OnboardingRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/register': {
      id: '/{-$locale}/register'
      path: '/register'
      fullPath: '/{-$locale}/register'
      preLoaderRoute: typeof Char123LocaleChar125RegisterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/reset-password': {
      id: '/{-$locale}/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125ResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/projects/': {
      id: '/{-$locale}/projects/'
      path: '/projects'
      fullPath: '/{-$locale}/projects/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/projects/$id': {
      id: '/{-$locale}/projects/$id'
      path: '/projects/$id'
      fullPath: '/{-$locale}/projects/$id'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/uploads/': {
      id: '/{-$locale}/uploads/'
      path: '/uploads'
      fullPath: '/{-$locale}/uploads/'
      preLoaderRoute: typeof Char123LocaleChar125UploadsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/uploads/$id': {
      id: '/{-$locale}/uploads/$id'
      path: '/uploads/$id'
      fullPath: '/{-$locale}/uploads/$id'
      preLoaderRoute: typeof Char123LocaleChar125UploadsIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/projects/$id/': {
      id: '/{-$locale}/projects/$id/'
      path: '/'
      fullPath: '/{-$locale}/projects/$id/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdRoute
    }
    '/{-$locale}/projects/$id/copilot': {
      id: '/{-$locale}/projects/$id/copilot'
      path: '/copilot'
      fullPath: '/{-$locale}/projects/$id/copilot'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdCopilotRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdRoute
    }
    '/{-$locale}/projects/$id/documents': {
      id: '/{-$locale}/projects/$id/documents'
      path: '/documents'
      fullPath: '/{-$locale}/projects/$id/documents'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdDocumentsRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdRoute
    }
    '/{-$locale}/projects/$id/submission': {
      id: '/{-$locale}/projects/$id/submission'
      path: '/submission'
      fullPath: '/{-$locale}/projects/$id/submission'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdSubmissionRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdRoute
    }
    '/{-$locale}/projects/$id/copilot/': {
      id: '/{-$locale}/projects/$id/copilot/'
      path: '/'
      fullPath: '/{-$locale}/projects/$id/copilot/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdCopilotIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdCopilotRoute
    }
    '/{-$locale}/projects/$id/copilot/$conversationId': {
      id: '/{-$locale}/projects/$id/copilot/$conversationId'
      path: '/$conversationId'
      fullPath: '/{-$locale}/projects/$id/copilot/$conversationId'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIdCopilotConversationIdRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsIdCopilotRoute
    }
  }
}

interface Char123LocaleChar125ProjectsIdCopilotRouteChildren {
  Char123LocaleChar125ProjectsIdCopilotConversationIdRoute: typeof Char123LocaleChar125ProjectsIdCopilotConversationIdRoute
  Char123LocaleChar125ProjectsIdCopilotIndexRoute: typeof Char123LocaleChar125ProjectsIdCopilotIndexRoute
}

const Char123LocaleChar125ProjectsIdCopilotRouteChildren: Char123LocaleChar125ProjectsIdCopilotRouteChildren =
  {
    Char123LocaleChar125ProjectsIdCopilotConversationIdRoute:
      Char123LocaleChar125ProjectsIdCopilotConversationIdRoute,
    Char123LocaleChar125ProjectsIdCopilotIndexRoute:
      Char123LocaleChar125ProjectsIdCopilotIndexRoute,
  }

const Char123LocaleChar125ProjectsIdCopilotRouteWithChildren =
  Char123LocaleChar125ProjectsIdCopilotRoute._addFileChildren(
    Char123LocaleChar125ProjectsIdCopilotRouteChildren,
  )

interface Char123LocaleChar125ProjectsIdRouteChildren {
  Char123LocaleChar125ProjectsIdCopilotRoute: typeof Char123LocaleChar125ProjectsIdCopilotRouteWithChildren
  Char123LocaleChar125ProjectsIdDocumentsRoute: typeof Char123LocaleChar125ProjectsIdDocumentsRoute
  Char123LocaleChar125ProjectsIdSubmissionRoute: typeof Char123LocaleChar125ProjectsIdSubmissionRoute
  Char123LocaleChar125ProjectsIdIndexRoute: typeof Char123LocaleChar125ProjectsIdIndexRoute
}

const Char123LocaleChar125ProjectsIdRouteChildren: Char123LocaleChar125ProjectsIdRouteChildren =
  {
    Char123LocaleChar125ProjectsIdCopilotRoute:
      Char123LocaleChar125ProjectsIdCopilotRouteWithChildren,
    Char123LocaleChar125ProjectsIdDocumentsRoute:
      Char123LocaleChar125ProjectsIdDocumentsRoute,
    Char123LocaleChar125ProjectsIdSubmissionRoute:
      Char123LocaleChar125ProjectsIdSubmissionRoute,
    Char123LocaleChar125ProjectsIdIndexRoute:
      Char123LocaleChar125ProjectsIdIndexRoute,
  }

const Char123LocaleChar125ProjectsIdRouteWithChildren =
  Char123LocaleChar125ProjectsIdRoute._addFileChildren(
    Char123LocaleChar125ProjectsIdRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AccountRoute: typeof Char123LocaleChar125AccountRoute
  Char123LocaleChar125DesignSystemRoute: typeof Char123LocaleChar125DesignSystemRoute
  Char123LocaleChar125ForgotPasswordRoute: typeof Char123LocaleChar125ForgotPasswordRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125NotificationsRoute: typeof Char123LocaleChar125NotificationsRoute
  Char123LocaleChar125OnboardingRoute: typeof Char123LocaleChar125OnboardingRoute
  Char123LocaleChar125RegisterRoute: typeof Char123LocaleChar125RegisterRoute
  Char123LocaleChar125ResetPasswordRoute: typeof Char123LocaleChar125ResetPasswordRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125ProjectsIdRoute: typeof Char123LocaleChar125ProjectsIdRouteWithChildren
  Char123LocaleChar125UploadsIdRoute: typeof Char123LocaleChar125UploadsIdRoute
  Char123LocaleChar125ProjectsIndexRoute: typeof Char123LocaleChar125ProjectsIndexRoute
  Char123LocaleChar125UploadsIndexRoute: typeof Char123LocaleChar125UploadsIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125AccountRoute: Char123LocaleChar125AccountRoute,
    Char123LocaleChar125DesignSystemRoute:
      Char123LocaleChar125DesignSystemRoute,
    Char123LocaleChar125ForgotPasswordRoute:
      Char123LocaleChar125ForgotPasswordRoute,
    Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
    Char123LocaleChar125NotificationsRoute:
      Char123LocaleChar125NotificationsRoute,
    Char123LocaleChar125OnboardingRoute: Char123LocaleChar125OnboardingRoute,
    Char123LocaleChar125RegisterRoute: Char123LocaleChar125RegisterRoute,
    Char123LocaleChar125ResetPasswordRoute:
      Char123LocaleChar125ResetPasswordRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125ProjectsIdRoute:
      Char123LocaleChar125ProjectsIdRouteWithChildren,
    Char123LocaleChar125UploadsIdRoute: Char123LocaleChar125UploadsIdRoute,
    Char123LocaleChar125ProjectsIndexRoute:
      Char123LocaleChar125ProjectsIndexRoute,
    Char123LocaleChar125UploadsIndexRoute:
      Char123LocaleChar125UploadsIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
