import { upload, type Project, type Submission } from "@hack4justice/db";
import { REQUIREMENTS, fieldsFor } from "@hack4justice/shared";
import { inArray } from "drizzle-orm";
import { strToU8, zipSync } from "fflate";

import { renderMarkdownPdf } from "../../agent/export";
import { db } from "../../db";
import type { Locale } from "../../i18n/index";
import { storage } from "../../storage";

/** Translated display strings supplied by the client: `service`, `req:<id>`, `field:<id>.<key>`, `status:<s>`, `rstatus:<s>`. */
export type ExportLabels = Record<string, string>;

interface ExportInput {
  project: Project;
  submission: Submission;
  format: "pdf" | "zip";
  locale: Locale;
  labels: ExportLabels;
}

const COPY: Record<Locale, Record<string, string>> = {
  fr: {
    title: "Dossier de dépôt",
    reference: "Référence",
    project: "Projet",
    service: "Service",
    destination: "Administration",
    submittedAt: "Déposé le",
    status: "Statut",
    receipt: "Récépissé",
    note: "Note",
    checklist: "Pièces du dossier",
    attached: "Fichier joint",
    disclaimer:
      "Document généré par Hack4Justice à partir des informations saisies par l’utilisateur. Il récapitule le dossier préparé ; le dépôt officiel est effectué par l’utilisateur sur le canal de l’administration.",
    generated: "Généré le",
  },
  en: {
    title: "Submission dossier",
    reference: "Reference",
    project: "Project",
    service: "Service",
    destination: "Agency",
    submittedAt: "Submitted on",
    status: "Status",
    receipt: "Receipt",
    note: "Note",
    checklist: "Dossier contents",
    attached: "Attached file",
    disclaimer:
      "Generated by Hack4Justice from the information entered by the user. It summarises the prepared dossier; the official submission is made by the user on the agency channel.",
    generated: "Generated on",
  },
  ar: {
    title: "ملف الإيداع",
    reference: "المرجع",
    project: "المشروع",
    service: "الخدمة",
    destination: "الإدارة",
    submittedAt: "تاريخ الإيداع",
    status: "الحالة",
    receipt: "الوصل",
    note: "ملاحظة",
    checklist: "محتوى الملف",
    attached: "الملف المرفق",
    disclaimer:
      "وثيقة أنشأها Hack4Justice من المعلومات التي أدخلها المستخدم. تلخّص الملف المُعدّ؛ ويتم الإيداع الرسمي من طرف المستخدم عبر قناة الإدارة.",
    generated: "أُنشئ في",
  },
};

const INTL: Record<Locale, string> = { fr: "fr-FR", en: "en-GB", ar: "ar-TN" };

function humanize(id: string): string {
  const words = id.toLowerCase().replace(/_/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/** Keeps file names safe inside the archive: no path separators, no control characters. */
function safeName(name: string): string {
  // eslint-disable-next-line no-control-regex
  return name.replace(/[\\/:*?"<>|\x00-\x1f]/g, "_").slice(0, 120) || "file.pdf";
}

function coverMarkdown({ project, submission, locale, labels }: ExportInput): string {
  const c = COPY[locale];
  const date = (value: Date) =>
    new Intl.DateTimeFormat(INTL[locale], { dateStyle: "long", timeStyle: "short" }).format(value);
  const label = (key: string, fallback: string) => labels[key] ?? fallback;
  const lines: string[] = [];
  lines.push(`# ${c.title}`, "");
  lines.push(`**${c.reference}:** ${submission.reference}`);
  lines.push(`**${c.project}:** ${project.name}`);
  lines.push(`**${c.destination}:** ${project.destination}`);
  lines.push(`**${c.service}:** ${label("service", humanize(submission.serviceId))}`);
  lines.push(`**${c.submittedAt}:** ${date(submission.submittedAt)}`);
  lines.push(`**${c.status}:** ${label(`status:${submission.status}`, humanize(submission.status))}`);
  if (submission.receipt) lines.push(`**${c.receipt}:** ${submission.receipt}`);
  if (submission.note) lines.push(`**${c.note}:** ${submission.note}`);
  lines.push("", "---", "", `## ${c.checklist}`, "");
  submission.snapshot.requirements.forEach((item, index) => {
    const def = REQUIREMENTS[item.requirementId];
    lines.push(`### ${index + 1}. ${label(`req:${item.requirementId}`, humanize(item.requirementId))}`, "");
    lines.push(`- **${c.status}:** ${label(`rstatus:${item.status}`, humanize(item.status))}`);
    if (item.upload) lines.push(`- **${c.attached}:** ${item.upload.filename}`);
    if (item.value) {
      const fields = fieldsFor(item.requirementId);
      for (const [key, value] of Object.entries(item.value)) {
        if (!value) continue;
        const known = fields.find((f) => f.key === key);
        const name = label(`field:${item.requirementId}.${key}`, known ? humanize(key) : key);
        lines.push(`- **${name}:** ${value}`);
      }
    }
    if (item.note) lines.push(`- **${c.note}:** ${item.note}`);
    if (def?.providedBy) lines.push(`- ${def.providedBy.entity}`);
    lines.push("");
  });
  lines.push("---", "", `*${c.disclaimer}*`, "", `*${c.generated} ${date(new Date())}*`);
  return lines.join("\n");
}

export async function exportSubmission(
  input: ExportInput,
): Promise<{ bytes: Uint8Array; contentType: string; filename: string }> {
  const cover = await renderMarkdownPdf(coverMarkdown(input));
  const base = input.submission.reference;
  if (input.format === "pdf") {
    return { bytes: cover, contentType: "application/pdf", filename: `${base}.pdf` };
  }
  const entries: Record<string, Uint8Array> = { [`${base}.pdf`]: cover };
  const uploadIds = input.submission.snapshot.requirements.flatMap((r) => (r.upload ? [r.upload.id] : []));
  if (uploadIds.length > 0) {
    const rows = await db
      .select({
        id: upload.id,
        filename: upload.filename,
        storageKey: upload.storageKey,
        userId: upload.userId,
      })
      .from(upload)
      .where(inArray(upload.id, uploadIds));
    for (const item of input.submission.snapshot.requirements) {
      if (!item.upload) continue;
      // Only the owner's files: the snapshot could reference an id that changed hands.
      const row = rows.find((r) => r.id === item.upload!.id && r.userId === input.project.userId);
      if (!row) continue;
      entries[`documents/${item.requirementId}/${safeName(row.filename)}`] = await storage.get(
        row.storageKey,
      );
    }
  }
  entries["README.txt"] = strToU8(`${input.submission.reference}\n${input.project.name}\n`);
  return { bytes: zipSync(entries, { level: 6 }), contentType: "application/zip", filename: `${base}.zip` };
}
